// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSchedule():Promise<string>;

export function CurrentTime():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsScheduled():Promise<boolean>;

export function RemainingTime():Promise<string>;

export function ScheduleDuration(arg1:string):Promise<string>;
