// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSchedule() {
  return window['go']['main']['App']['CancelSchedule']();
}

export function CurrentTime() {
  return window['go']['main']['App']['CurrentTime']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsScheduled() {
  return window['go']['main']['App']['IsScheduled']();
}

export function RemainingTime() {
  return window['go']['main']['App']['RemainingTime']();
}

export function ScheduleDuration(arg1) {
  return window['go']['main']['App']['ScheduleDuration'](arg1);
}
